### ISSUE TITLE
Support for Home Assistant Auto Discovery

### ISSUE THREAD

**Issue by nanosonde** [gbeine/knx2mqtt#1]
Does it support HA auto discovery of MQTT components as mentioned here?

https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by nanosonde** [comment]
This might also be helpful: https://github.com/plapointe6/HAMqttDevice

**Comment by gbeine** [comment]
Feel free to add it, I don't use HA anymore as it did not run as stable as I require it for solution for home automation.

**Comment by nanosonde** [comment]
Sad to read.
I am using HA since two years now. IMHO the best open source smart home software on the market. Have used OH3 for two years before. 🤮
Using HA with KNX (~80 devices), Sonos, Hue, Buderus, Synology DSM, Ecowitt and Reolink cameras. Everything runs smoothly as it should. HAOS is running in a VM on the synology NAS DS1821+.
Maintenance of the software is superior.
Big community… and so on… 😉
