### ISSUE TITLE
unknown error knx2mqtt not run on raspberry python 3.9

### ISSUE THREAD

**Issue by pythonlubo** [gbeine/knx2mqtt#7]
Nach erfolgreicher Installation und Konfiguration nach Anleitung endet  das script mit einer Fehlermeldung.
(siehe pics) - woran kann das liegen...?
Vielen Dank -

![knx2mqtt-yaml](https://user-images.githubusercontent.com/130909264/232312922-26bc354f-96d5-4264-8173-e0bd62690ade.png)
![knx2mqtt-Fehlermeldung-01](https://user-images.githubusercontent.com/130909264/232312923-cb39f929-c9c9-4533-8a22-7abbd159b717.png)

**Comment by pythonlubo** [comment]
Nach der Anpassung gemäß "mayrstefan" startet das tool - vielen Dank -
Allerdings werden 2 weitere Fehler ausgegeben (siehe Screenshots)
Ich versuche zunächst einen Temperaturwert auf den Mosquitto-Broker zu bekommen.
Der Datenpunkttyp in der ETS5 lautet 9.001 Temperatur in °C und läuft hier sauber.
knx2mqtt kann jedoch diesen Datenpunkttyp nicht erkennen und leitet auch nichts an den Broker weiter.
Ich habe auch DTPTemperatureA und "F" probiert - erfolglos....
Weiss jemand, wo es hier "hängt"...?
Vielen Dank -
![Error-Datenpunkttyp](https://user-images.githubusercontent.com/130909264/232696549-6035af3b-b47c-4e35-aad4-d9d3de1a7c89.png)
![NameError-'traceback'](https://user-images.githubusercontent.com/130909264/232696585-d3d9ff0a-ed56-4780-911f-51e23a121559.png)

**Comment by farmio** [comment]
This project seems to be built on xknx 1.2 currently. You try to run it with an incompatible version (probably 2.9.0). 
To fix this downgrade your local xknx. Otherwise update the code to be compatible with recent xknx versions.

It would also be a good idea to pin the requirement.

**Comment by gbeine** [comment]
Yep, it seems, versions are not compatible.
With the last major update of knx2mqtt, I've updated the dependency to xknx.
As xknx has no stable API I have to update knx2mqtt when I find time for it.
As the comment in main branch states, it's currently based on 0.22 - newer versions might work.

**Comment by farmio** [comment]
@gbeine xknx tries to adhere to semver. So minor version upgrades shouldn't be a problem.  You might want to pin the version your script is built on.

**Comment by gbeine** [comment]
been there, done that, you're right: it tries

**Comment by gbeine** [comment]
> You might want to pin the version your script is built on.

No need to become passive-agressive, be kind. :-)

**Comment by farmio** [comment]
Sorry, I really didn't mean to. Maybe this got lost in translation.
It should only be a friendly suggestion to ensure compatibility and resilience against breaking API changes.

**Comment by gbeine** [comment]
No hard feelings.
In the version, that was used when the problem was posted, requirements.txt set xknx to <=0.18
Unfortunately, it was ignored, so forcing the version was not a solution for this problem.
I removed the version sticker later by intent.
